# -*- coding: utf-8 -*-
"""MY_HW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1opVpJp-nzWp83p-IOvvdYn78wWeeU5GE
"""

#Ian Conceicao
#505153981
#Homework 22

# This code was adapted from course material by Jenna Wiens (UMichigan).

# python libraries
import os

# numpy libraries
import numpy as np

# matplotlib libraries
import matplotlib.pyplot as plt

#Adding my own import here:
from time import time

# To add your own Drive Run this cell.
from google.colab import drive
drive.mount('/content/drive')

######################################################################
# classes
######################################################################


class Data:
    def __init__(self, X=None, y=None):
        """
        Data class.
        
        Attributes
        --------------------
            X       -- numpy array of shape (n,d), features
            y       -- numpy array of shape (n,), targets
        """

        # n = number of examples, d = dimensionality
        self.X = X
        self.y = y

    def load(self, filename):
        """
        Load csv file into X array of features and y array of labels.
        
        Parameters
        --------------------
            filename -- string, filename
        """


        # load data
        with open(filename, "r") as fid:
            data = np.loadtxt(fid, delimiter=",")

        # separate features and labels
        self.X = data[:, :-1]
        self.y = data[:, -1]

    def plot(self, **kwargs):
        """Plot data."""

        if "color" not in kwargs:
            kwargs["color"] = "b"

        plt.scatter(self.X, self.y, **kwargs)
        plt.xlabel("x", fontsize=16)
        plt.ylabel("y", fontsize=16)
        plt.show()

# wrapper functions around Data class
def load_data(filename):
    data = Data()
    data.load(filename)
    return data


def plot_data(X, y, **kwargs):
    data = Data(X, y)
    data.plot(**kwargs)

class PolynomialRegression:
    def __init__(self, m=1, reg_param=0):
        """
        Ordinary least squares regression.
        
        Attributes
        --------------------
            coef_   -- numpy array of shape (d,)
                       estimated coefficients for the linear regression problem
            m_      -- integer
                       order for polynomial regression
            lambda_ -- float
                       regularization parameter
        """

        # self.coef_ represents the weights of the regression model
        self.coef_ = None
        self.m_ = m
        self.lambda_ = reg_param

    def generate_polynomial_features(self, X):
        """
        Maps X to an mth degree feature vector e.g. [1, X, X^2, ..., X^m].
        
        Parameters
        --------------------
            X       -- numpy array of shape (n,1), features
        
        Returns
        --------------------
            Phi     -- numpy array of shape (n,(m+1)), mapped features
        """

        n, d = X.shape

        ### ========== TODO : START ========== ###
        # part b: modify to create matrix for simple linear model
        # part g: modify to create matrix for polynomial model
        
        #Having a problem where we are asked to generate data multiple times for
        #the same data

        m = self.m_
        #Check if the data is already good:
        if np.shape(X)[1] == m + 1:
          return X
        Phi = np.ones_like(X) #Make first column of 1's

        for i in range(0, m):
            j = i+1
            Phi = np.hstack((Phi, X**j))



        ### ========== TODO : END ========== ###

        return Phi

    def fit_GD(self, X, y, eta=None, eps=0, tmax=10000, verbose=False):
        """
        Finds the coefficients of a {d-1}^th degree polynomial
        that fits the data using least squares batch gradient descent.
        
        Parameters
        --------------------
            X       -- numpy array of shape (n,d), features
            y       -- numpy array of shape (n,), targets
            eta     -- float, step size
            eps     -- float, convergence criterion
            tmax    -- integer, maximum number of iterations
            verbose -- boolean, for debugging purposes
        
        Returns
        --------------------
            self    -- an instance of self
        """
        begin = time()
        if self.lambda_ != 0:
            raise Exception("GD with regularization not implemented")

        X = self.generate_polynomial_features(X)  # map features
        n, d = X.shape
        eta_input = eta
        self.coef_ = np.zeros(d)  # coefficients
        err_list = np.zeros((tmax, 1))  # errors per iteration

        # GD loop
        for t in range(tmax):
            ### ========== TODO : START ========== ###
            # part f: update step size
            # change the default eta in the function signature to 'eta=None'
            # and update the line below to your learning rate function
            if eta_input is None:
                eta = 1.0 / (1.0 + float(t))  # change this line
            else:
                eta = eta_input
            ### ========== TODO : END ========== ###

            ### ========== TODO : START ========== ###
            # part d: update w (self.coef_) using one step of GD
            # hint: you can write simultaneously update all w using vector math
            
            error = self.predict(X) - y
            gradient = np.dot(X.T, error)
            self.coef_ = self.coef_ - (2 * eta * gradient)

            # track error
            # hint: you cannot use self.predict(...) to make the predictions
            y_pred = np.dot(X, self.coef_)
            err_list[t] = np.sum(np.power(y - y_pred, 2)) / float(n)
            ### ========== TODO : END ========== ###

            # stop?
            if t > 0 and abs(err_list[t] - err_list[t - 1]) <= eps:
                break

            # debugging
            # debugging
            if verbose :
                x = np.reshape(X[:,1], (n,1))
                cost = self.cost(x,y)
                print ("iteration: %d, cost: %f" % (t+1, cost))
        end = time()
        print("-----")
        print("Learning Rate = {}".format(eta))
        print("Iterations = {}".format(t+1))
        print("Cost = {}".format(self.cost(X,y)))
        print("Coefficients:")
        print(self.coef_)
        print("Time {}".format(str(end-begin)))


        return self

    def fit(self, X, y, l2regularize=None):
        """
        Finds the coefficients of a {d-1}^th degree polynomial
        that fits the data using the closed form solution.
        
        Parameters
        --------------------
            X       -- numpy array of shape (n,d), features
            y       -- numpy array of shape (n,), targets
            l2regularize    -- set to None for no regularization. set to positive double for L2 regularization
                
        Returns
        --------------------        
            self    -- an instance of self
        """

        X = self.generate_polynomial_features(X)  # map features

        ### ========== TODO : START ========== ###
        # part e: implement closed-form solution
        # hint: use np.dot(...) and np.linalg.pinv(...)
        #       be sure to update self.coef_ with your solution
        begin = time()
        self.coef_ = np.linalg.pinv((np.dot(X.T, X))).dot(X.T).dot(y)
        end = time()
    

        print("-----")
        print("Cost = {}".format(self.cost(X,y)))
        print("Coefficients:")
        print(self.coef_)
        print("Time {}".format(str(end-begin)))


        ### ========== TODO : END ========== ###

    def predict(self, X):
        """
        Predict output for X.
        
        Parameters
        --------------------
            X       -- numpy array of shape (n,d), features
        
        Returns
        --------------------
            y       -- numpy array of shape (n,), predictions
        """
        if self.coef_ is None:
            raise Exception("Model not initialized. Perform a fit first.")
        X = self.generate_polynomial_features(X)  # map features
        ### ========== TODO : START ========== ###
        # part c: predict y
        y = np.dot(X, self.coef_)
        ### ========== TODO : END ========== ###

        return y

    def cost(self, X, y):
        """
        Calculates the objective function.
        
        Parameters
        --------------------
            X       -- numpy array of shape (n,d), features
            y       -- numpy array of shape (n,), targets
        
        Returns
        --------------------
            cost    -- float, objective J(w)
        """
        ### ========== TODO : START ========== ###
        # part d: compute J(w)
        y_hat = self.predict(X)
        mean_squares = (y - y_hat) ** 2
        cost = sum(mean_squares)

        ### ========== TODO : END ========== ###
        return cost

    def rms_error(self, X, y):
        """
        Calculates the root mean square error.
        
        Parameters
        --------------------
            X       -- numpy array of shape (n,d), features
            y       -- numpy array of shape (n,), targets
        
        Returns
        --------------------
            error   -- float, RMSE
        """
        ### ========== TODO : START ========== ###
        # part h: compute RMSE
        J = self.cost(self.generate_polynomial_features(X), y)
        error = np.sqrt(J/X.shape[0])

        ### ========== TODO : END ========== ###
        return error

    def plot_regression(self, xmin=0, xmax=1, n=50, **kwargs):
        """Plot regression line."""
        if "color" not in kwargs:
            kwargs["color"] = "r"
        if "linestyle" not in kwargs:
            kwargs["linestyle"] = "-"

        X = np.reshape(np.linspace(0, 1, n), (n, 1))
        y = self.predict(X)
        plot_data(X, y, **kwargs)
        plt.show()



######################################################################
# main
######################################################################

def main():
    # load data with correct file path

    ### ========== TODO : START ========== ###
    data_directory_path = '/content/drive/My Drive/01 Classes/Junior Q1/CS 146/Homeworks/HW2'
    ### ========== TODO : END ========== ###

    train_data = load_data(os.path.join(data_directory_path, "train.csv"))
    test_data = load_data(os.path.join(data_directory_path,"test.csv"))

    ### ========== TODO : START ========== ###
    # part a: main code for visualizations
    print("Visualizing data...")
    plot_data(train_data.X, train_data.y)
    plot_data(test_data.X, test_data.y)

    
    

    ### ========== TODO : END ========== ###

    ### ========== TODO : START ========== ###
    # parts b-f: main code for linear regression
    print("Investigating linear regression...")
    #Find cost of linear
    print("Finding the cost an untrained linear fit.")
    model = PolynomialRegression(1)
    model.coef_ = np.zeros(2)
    c = model.cost (train_data.X, train_data.y)
    print(f'model_cost:{c}')

    rates = [0.000001, 0.00001, 0.001, 0.0168]
    print("Running gradient descent:")
    for rate in rates:
        model = PolynomialRegression(1)
        model.fit_GD(train_data.X, train_data.y, rate)

    print("Running closed form solution")
    model = PolynomialRegression(1)
    model.fit(train_data.X, train_data.y)

    print("Running with variable learning rate")
    model = PolynomialRegression(1)
    model.fit_GD(train_data.X, train_data.y)

    
    ### ========== TODO : END ========== ###

    ### ========== TODO : START ========== ###
    # parts g-i: main code for polynomial regression
    print("Investigating polynomial regression...")

    print("Testing m-order polynomials:")

    test_errors = []
    train_errors = []
    orders = [*range(0,11)]

    bestError = None
    bestM = None

    for orderM in orders:
      print("Ran")
      model = PolynomialRegression(orderM)
      model.fit(train_data.X, train_data.y)
      RMSE_train = model.rms_error(train_data.X, train_data.y)
      RMSE_test = model.rms_error(test_data.X, test_data.y)
      
      train_errors.append(RMSE_train)
      test_errors.append(RMSE_test)

      if bestError == None or RMSE_test < bestError:
        bestError = RMSE_test
        bestM = orderM
    
    plt.figure()
    plt.plot(orders, test_errors, label="Test Error")
    plt.plot(orders, train_errors, label="Training Error")
    plt.legend()
    plt.xlabel("Polynomial Degree")
    plt.ylabel("Root Mean Square Error (RMSE)")
    plt.show()

    print("Best order polynomial was: {} with an error of {}".format(bestM,bestError))
  


    ### ========== TODO : END ========== ###

    print("Done!")

if __name__ == "__main__":
    main()